---
- name: install nova related packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient
    - python-oslo.rootwrap
    - nova-compute
    - sysfsutils

- name: update nova conf
  template: src=nova.conf dest=/etc/nova/nova.conf backup=yes
  notify:
    - restart nova-api
    - restart nova-cert
    - restart nova-consoleauth
    - restart nova-scheduler
    - restart nova-conductor
    - restart nova-novncproxy
    - remove nova-sqlite-db
    - restart nova-compute

- name: nova db sync
  command: su -s /bin/sh -c "nova-manage db sync" nova
  notify:
    - restart nova-api
    - restart nova-cert
    - restart nova-consoleauth
    - restart nova-scheduler
    - restart nova-conductor
    - restart nova-novncproxy

- name: create nova-compute.conf
  template: src=nova-compute.conf dest=/etc/nova/nova-compute.conf backup=yes

- name: nova compute restart
  service: name=nova-compute state=restarted

- meta: flush_handlers
